var _troqck=_troqck||0;
(function(w,l,f,d,H,q,u){function D(c){try{var a=Array.prototype.slice.call(arguments,0);c=a.shift();switch(c){case "init":if(!d.tagid)throw"tagid is missing";v=!0;break;case "session_ttl":a[0]&&(d.session_ttl=a[0]);break;case "tag":m=[];var b=a[0],a=[],g;for(g in b)if(b.hasOwnProperty(g))if("rtg"===g.substring(0,3))m.push(x(g,[b[g]])),a.push([g,[b[g]]]);else if("exclusion"===g)m.push("exclusion=1"),a.push([g,["1"]]);else if("m5e"===g||"email"===g||"sha256"===g)m.push(g+"="+b[g]),a.push([g,[b[g]]]);
var e=y(d.session_ttl||1800);t("__trossion",e,395);m.push("trossion="+e);a.push(["r1",[h]]);a.push(["vruid",[q]]);v&&(_troqck=1,z(m));d.segq.queue?d.segq.tag?d.segq.tag.apply(d.segq,b):d.segq.queue.push(b):d.segq.push.apply(d.segq,a)}}catch(E){k(E,14)}}function I(c){try{var a=c;a.queue&&(a=a.queue);for(var b=0;b<a.length;b++)if(a[b]&&a[b][0]&&("tagid"===a[b][0]||"init"===a[b][0])&&""!==a[b][1]){var d=a[b][1].split("-")[1];if(!d||32!==d.length)throw"Tagid is invalid";c.tagid=a[b][1];return}throw"Tagid is missing";
}catch(e){k(e,13)}}var A,F=!1,h="",r=f;f=r.hostname.split(".").reverse();d.etag=u.substring(0,7);A=2<f.length&&3>=f[1].length&&2>=f[0].length?"."+f[2]+"."+f[1]+"."+f[0]:"."+f[1]+"."+f[0];w!==top&&l.referrer&&""!==l.referrer&&(r=l.referrer);var x=function(c,a){for(var b="",d=0;d<a.length;d++)0<d&&(b+="|"),b+=a[d];try{b=c+"="+encodeURIComponent(b)}catch(e){b=c+"="+escape(b)}return b};d.urlize=x;var n=function(c){var a,b,d,e=l.cookie.split(";");for(a=0;a<e.length;a++)if(b=e[a].substr(0,e[a].indexOf("=")),
d=e[a].substr(e[a].indexOf("=")+1),b=b.replace(/^\s+|\s+$/g,""),b===c)try{return decodeURIComponent(d)}catch(E){return unescape(d)}return""};d.getCookie=n;var t=function(c,a,b){var d=new Date;d.setDate(d.getDate()+b);try{a=encodeURIComponent(a)}catch(p){a=escape(a)}var e=a;b=null===b?"":"; expires="+d.toUTCString();e=e+b+("; domain="+A+"; path=/");l.cookie=c+"="+e;try{if(""===n(c)||n(c)!=a){var f=w.location.hostname;if(1===f.split(".").length)l.cookie=c+"="+a+b+"; path=/";else{var h=f.split(".");
h.shift();var m="."+h.join(".");l.cookie=c+"="+a+b+"; path=/; domain="+m;if(""===n(c)||n(c)!=a)l.cookie=c+"="+a+b+"; path=/; domain="+A}}}catch(p){k(p,1)}};d.setCookie=t;var y=function(c){var a=n("__trossion"),b=Math.round((new Date).getTime()/1E3-d.deltaTimeStamp);""===a?(a=[],a.push(b),a.push(c),a.push(1),a.push(""),a.push(h+":"+b),a.push(b),a.push(1)):(a=a.split("_"),b-a[5]<=c&&b>=a[5]?(a[1]=c,a[5]=b,a[6]++):(b<a[5]&&k("Negative session time &trossion="+a.join("_")+"&duration="+(b-a[5])+"&userAgent="+
navigator.userAgent,2),a[1]=c,a[2]++,a[3]=a[4],a[4]=h+":"+b,a[5]=b,a[6]=1));return a.join("_")};d.getSessionValue=y;var z=function(c,a){try{if(null==d.tagid||""===d.tagid)throw"tagid is missing";for(var b="tagid="+d.tagid+"&",b=b+("vck="+H+"&"),b=b+("r1="+h+"&"),b=b+("vruid="+q+"&");0<c.length;)b+=c.shift()+"&";if(null!==r&&""!==r){b+="u=";try{b+=encodeURIComponent(r)}catch(g){b+=escape(r)}b+="&"}b+="etag="+d.etag;b+=(d.version?"_"+d.version:"")+"&";b+="rnd="+Math.round(2E9*Math.random());b="//"+
(a||"mmtro.com")+"/p?"+b;(new Image(1,1)).src=b}catch(g){k(g,3)}};d.troPix=z;d.push=function(){try{for(var c=0;c<arguments.length;c++)m.push(arguments[c])}catch(p){k(p,4)}for(var c=[],a=[],b=[];0<m.length;)try{var g=m.shift(),e=g.shift();if(!e)throw"empty array in taggage";var e=e.toLowerCase(),f=g;if("tagid"===e){if(!d.tagid)throw"tagid is missing";v=!0}else if("rtg"===e.substring(0,3)||-1!==e.indexOf("_")){0===e.indexOf("_")&&(e=e.substring(1,e.length));var l=x(e,f);a.push(l);b.push([e,f])}else"exclusion"===
e?(a.push("exclusion=1"),b.push([e,["1"]])):"m5e"===e||"email"===e||"sha256"===e?(a.push(e+"="+f[0]),b.push([e,f])):c.push(e+"="+f[0])}catch(p){k(p,5)}0<c.length&&k("wrong params in taggage "+c.join("&"),12);try{if(0<a.length||v){0===_troqck&&(_troqck=1);var n=y(d.session_ttl||1800);t("__trossion",n,395);a.push("trossion="+n);z(a);b.push(["r1",[h]]);b.push(["vruid",[q]]);d.segq.push.apply(d.segq,b)}}catch(p){k(p,6)}};d.callTro=D;d.unqueue=function(c,a){var b=Math.round((new Date).getTime()/1E3);c.deltaTimeStamp=
b-(a||b);try{if(c.queue)for(;c.queue.length;){var d=c.queue.shift();D.apply(this,d)}else m=Array.prototype.splice.call(c,0),c.push()}catch(e){k(e,7)}};var B=function(c){var a=l.createElement("script");a.type="text/javascript";a.async=!0;a.src=c;c=l.getElementsByTagName("script")[0];c.parentNode.insertBefore(a,c)};d.callSeg=function(){try{B("//mmtro.com/seg/"+d.tagid.split("-")[0]+".js")}catch(c){k(c,8)}};d.callSync=function(){try{n("__troSYNC")||B("//mmtro.com/sync.js")}catch(c){k(c,9)}};d.jarSyncMMTRO=
function(c){try{t("__troRUID",c,395)}catch(a){k(a,10)}};var k=function(c,a){c=c.message||c;c=encodeURIComponent(c.replace(/ /g,"_"));var b="//err.mmtro.com/error?f=tro.js&u="+encodeURIComponent(w.location.href)+"&message="+c+"&try="+a+"&etag="+d.etag;(new Image(1,1)).src=b};try{var m=[],v=!1;if(!_troqck){u=!1;d.segq=d.segq||[];var G=l.getElementsByTagName("script");for(f=0;f<G.length;f++){var C=G[f].src;if(void 0!=C&&""!=C&&-1<C.lastIndexOf("//mmtro.com/tro.js")){u=!0;break}}if(!u)throw"tro.js is not loaded properly";
if(null==q||""==q)throw"vruid is invalid";h=n("__troRUID");if(null==h||""==h)F=!0,h=q;F&&t("__troRUID",h,395);I(d);null!=d.tagid&&""!=d.tagid&&B("//mmtro.com/trojs/"+d.tagid+"/"+h+"/"+q+"/exec.js")}}catch(c){k(c,11)}})
(window, document, location, _troq, 1, "b6bc93a9-5675-4e06-ae68-04ab8bb83907", "1c05aaefe56498066b4ac8e41c757ef3");